//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Index", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andalusian Cortijo.
        /// </summary>
        internal static string acccortijoandaluz {
            get {
                return ResourceManager.GetString("acccortijoandaluz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOK NOW.
        /// </summary>
        internal static string accreservar {
            get {
                return ResourceManager.GetString("accreservar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tepees.
        /// </summary>
        internal static string acctipis {
            get {
                return ResourceManager.GetString("acctipis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Homes.
        /// </summary>
        internal static string accwakanacasas {
            get {
                return ResourceManager.GetString("accwakanacasas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yurts.
        /// </summary>
        internal static string accyurtas {
            get {
                return ResourceManager.GetString("accyurtas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Us.
        /// </summary>
        internal static string acercadenos {
            get {
                return ResourceManager.GetString("acercadenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “Wakana offers various activities ranging from relaxing walks to games and sports that promote an active and healthy lifestyle. All activities aim at improving fundamental values such as self-confidence and team building whilst developing positive attitudes towards social communities and nature.”.
        /// </summary>
        internal static string actdisponesmosdeuna {
            get {
                return ResourceManager.GetString("actdisponesmosdeuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities Schedule.
        /// </summary>
        internal static string acthorario {
            get {
                return ResourceManager.GetString("acthorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string actividades {
            get {
                return ResourceManager.GetString("actividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string actividadestitulo {
            get {
                return ResourceManager.GetString("actividadestitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICES for Groups up to 7 persons.
        /// </summary>
        internal static string actprecios7 {
            get {
                return ResourceManager.GetString("actprecios7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICES for Groups from 8 up to 17 persons.
        /// </summary>
        internal static string actprecios8 {
            get {
                return ResourceManager.GetString("actprecios8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gisela Pulido Pro Center Prices.
        /// </summary>
        internal static string actpreciosgisela {
            get {
                return ResourceManager.GetString("actpreciosgisela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed-toe sports shoes.
        /// </summary>
        internal static string actspartancalzado {
            get {
                return ResourceManager.GetString("actspartancalzado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spare pair of shoes and clothing for after
        ///the activity.
        /// </summary>
        internal static string actspartanropaycalzado {
            get {
                return ResourceManager.GetString("actspartanropaycalzado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string actspartantrailobs {
            get {
                return ResourceManager.GetString("actspartantrailobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REQUIREMENTS.
        /// </summary>
        internal static string actspartantrailrequisitos {
            get {
                return ResourceManager.GetString("actspartantrailrequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accommodation.
        /// </summary>
        internal static string alojamientos {
            get {
                return ResourceManager.GetString("alojamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andalusian Cortijo.
        /// </summary>
        internal static string andacortijoandaluz {
            get {
                return ResourceManager.GetString("andacortijoandaluz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICES.
        /// </summary>
        internal static string andaprecios {
            get {
                return ResourceManager.GetString("andaprecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture the flag.
        /// </summary>
        internal static string arcatrapa {
            get {
                return ResourceManager.GetString("arcatrapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team battle.
        /// </summary>
        internal static string arcguerra {
            get {
                return ResourceManager.GetString("arcguerra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduction to bow and arrow.
        /// </summary>
        internal static string arcintroduccion {
            get {
                return ResourceManager.GetString("arcintroduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free-for-all.
        /// </summary>
        internal static string arctodoscontratodos {
            get {
                return ResourceManager.GetString("arctodoscontratodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THE ADVENTURE STARTS HERE.
        /// </summary>
        internal static string aventuracomienza {
            get {
                return ResourceManager.GetString("aventuracomienza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEGAL NOTICE.
        /// </summary>
        internal static string avisolegal {
            get {
                return ResourceManager.GetString("avisolegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2017 DATES.
        /// </summary>
        internal static string bocalanfecha {
            get {
                return ResourceManager.GetString("bocalanfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MORE INFO.
        /// </summary>
        internal static string bocalanmasinfo {
            get {
                return ResourceManager.GetString("bocalanmasinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string bookingcancel {
            get {
                return ResourceManager.GetString("bookingcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOK WAKANA.
        /// </summary>
        internal static string bookwakana {
            get {
                return ResourceManager.GetString("bookwakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buho real.
        /// </summary>
        internal static string buhoreal {
            get {
                return ResourceManager.GetString("buhoreal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bocalan Camps.
        /// </summary>
        internal static string campamentobocalantitulo {
            get {
                return ResourceManager.GetString("campamentobocalantitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camps.
        /// </summary>
        internal static string campamentos {
            get {
                return ResourceManager.GetString("campamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bocalan Camps.
        /// </summary>
        internal static string campamentosbocalan {
            get {
                return ResourceManager.GetString("campamentosbocalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a School Camps.
        /// </summary>
        internal static string campamentosescolares {
            get {
                return ResourceManager.GetString("campamentosescolares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spartan Race Camps.
        /// </summary>
        internal static string campamentosspartanrace {
            get {
                return ResourceManager.GetString("campamentosspartanrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake Summers Camps.
        /// </summary>
        internal static string campamentosveranowakana {
            get {
                return ResourceManager.GetString("campamentosveranowakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake Camps.
        /// </summary>
        internal static string campscampamentoswakanalake {
            get {
                return ResourceManager.GetString("campscampamentoswakanalake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2017 DATES.
        /// </summary>
        internal static string campsfechas2017 {
            get {
                return ResourceManager.GetString("campsfechas2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MORE INFO.
        /// </summary>
        internal static string campsmasinfo {
            get {
                return ResourceManager.GetString("campsmasinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The establishment will charge 100% of the first night at least 10 days before arrival..
        /// </summary>
        internal static string cancelpolelestable {
            get {
                return ResourceManager.GetString("cancelpolelestable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you cancel or modify the booking 10 days before arrival date, no fees will be charged by the establishment..
        /// </summary>
        internal static string cancelpolsicancelas1 {
            get {
                return ResourceManager.GetString("cancelpolsicancelas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you cancel or modify the booking after deadline (less than 10 days from arrival), the establishment will charge 100% of the fee for the first night..
        /// </summary>
        internal static string cancelpolsicancelas2 {
            get {
                return ResourceManager.GetString("cancelpolsicancelas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you don’t turn up, the establishment will charge the full stay..
        /// </summary>
        internal static string cancelpolsinotepresentas {
            get {
                return ResourceManager.GetString("cancelpolsinotepresentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelation Policy.
        /// </summary>
        internal static string cancelpoltitulo {
            get {
                return ResourceManager.GetString("cancelpoltitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good physical health.
        /// </summary>
        internal static string canopybuenaformafisica {
            get {
                return ResourceManager.GetString("canopybuenaformafisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed-toe sports shoes.
        /// </summary>
        internal static string canopycalzadodeportivo {
            get {
                return ResourceManager.GetString("canopycalzadodeportivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum height of 140cm.
        /// </summary>
        internal static string canopymedimasde140 {
            get {
                return ResourceManager.GetString("canopymedimasde140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REQUIREMENTS.
        /// </summary>
        internal static string canopyparkrequisitos {
            get {
                return ResourceManager.GetString("canopyparkrequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum weight of 120kg.
        /// </summary>
        internal static string canopypesarmenos120 {
            get {
                return ResourceManager.GetString("canopypesarmenos120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partners.
        /// </summary>
        internal static string colaboradores {
            get {
                return ResourceManager.GetString("colaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let yourself inspire by the beauty and unique energy that drives Wakana..
        /// </summary>
        internal static string comdejateseducirpor {
            get {
                return ResourceManager.GetString("comdejateseducirpor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Bodyself.
        /// </summary>
        internal static string comelyocorporal {
            get {
                return ResourceManager.GetString("comelyocorporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Spiritual Self.
        /// </summary>
        internal static string comelyoespiritual {
            get {
                return ResourceManager.GetString("comelyoespiritual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Intellectual Self.
        /// </summary>
        internal static string comelyointelectual {
            get {
                return ResourceManager.GetString("comelyointelectual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explore your inner spirit through nature and find clarity for your personal and professional goals..
        /// </summary>
        internal static string comexploratuespiritualidad {
            get {
                return ResourceManager.GetString("comexploratuespiritualidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OUR MISSION.
        /// </summary>
        internal static string comnuestramision {
            get {
                return ResourceManager.GetString("comnuestramision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OUR VISION.
        /// </summary>
        internal static string comnuestravision {
            get {
                return ResourceManager.GetString("comnuestravision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What we live for.
        /// </summary>
        internal static string comporloquevivimos {
            get {
                return ResourceManager.GetString("comporloquevivimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reconnect with your “body self” and activate the full strength and capabilities of your body..
        /// </summary>
        internal static string comreconecta {
            get {
                return ResourceManager.GetString("comreconecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To become the leader in connecting people to nature, sports and arts..
        /// </summary>
        internal static string comserloslideres {
            get {
                return ResourceManager.GetString("comserloslideres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bring harmony to every man, woman and child visiting Wakana, embrace nature, deliver happiness, inspire everyone..
        /// </summary>
        internal static string comtraerarmonia {
            get {
                return ResourceManager.GetString("comtraerarmonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Community.
        /// </summary>
        internal static string comunidad {
            get {
                return ResourceManager.GetString("comunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “Wakana Lake is a place of harmony, well being and outdoor activities established in the heart of nature’s surroundings. Discover….”.
        /// </summary>
        internal static string comwakanalakeesunlugar {
            get {
                return ResourceManager.GetString("comwakanalakeesunlugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAL CONDITIONS.
        /// </summary>
        internal static string condicionesgenerales {
            get {
                return ResourceManager.GetString("condicionesgenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAL CONDITIONS.
        /// </summary>
        internal static string contactconsultasgenerales {
            get {
                return ResourceManager.GetString("contactconsultasgenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACT US.
        /// </summary>
        internal static string contactcontactanos {
            get {
                return ResourceManager.GetString("contactcontactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Directions.
        /// </summary>
        internal static string contactdireccion {
            get {
                return ResourceManager.GetString("contactdireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Careers.
        /// </summary>
        internal static string contactempleos {
            get {
                return ResourceManager.GetString("contactempleos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spain.
        /// </summary>
        internal static string contactespaña {
            get {
                return ResourceManager.GetString("contactespaña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interested in partnering with us? - GET IN TOUCH.
        /// </summary>
        internal static string contactestasinteresado {
            get {
                return ResourceManager.GetString("contactestasinteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let&apos;s talk.
        /// </summary>
        internal static string contacthablemos {
            get {
                return ResourceManager.GetString("contacthablemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Us!.
        /// </summary>
        internal static string contactmandanosemail {
            get {
                return ResourceManager.GetString("contactmandanosemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our Location.
        /// </summary>
        internal static string contactnuestralocalizacion {
            get {
                return ResourceManager.GetString("contactnuestralocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACT.
        /// </summary>
        internal static string contactofooter {
            get {
                return ResourceManager.GetString("contactofooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tel.
        /// </summary>
        internal static string contacttelefono {
            get {
                return ResourceManager.GetString("contacttelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andalusian Coritjo.
        /// </summary>
        internal static string cortijoandaluz {
            get {
                return ResourceManager.GetString("cortijoandaluz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explore the Green Way Dos Bahías from Los Barrios to Puerto Real with a total of 93km.
        /// </summary>
        internal static string cyclingdisfruta {
            get {
                return ResourceManager.GetString("cyclingdisfruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mountain bike (MTB).
        /// </summary>
        internal static string cyclingmountain {
            get {
                return ResourceManager.GetString("cyclingmountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All riding levels.
        /// </summary>
        internal static string cyclingtodoslosniveles {
            get {
                return ResourceManager.GetString("cyclingtodoslosniveles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DAY.
        /// </summary>
        internal static string dia {
            get {
                return ResourceManager.GetString("dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WHERE HARMONY FINDS YOU.
        /// </summary>
        internal static string encuentralaarmonia {
            get {
                return ResourceManager.GetString("encuentralaarmonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        internal static string equipo {
            get {
                return ResourceManager.GetString("equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string eventos {
            get {
                return ResourceManager.GetString("eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string eventosevents {
            get {
                return ResourceManager.GetString("eventosevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WITH YOUR TEAM.
        /// </summary>
        internal static string experienciacontuequipo {
            get {
                return ResourceManager.GetString("experienciacontuequipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WITH YOUR FAMILY.
        /// </summary>
        internal static string experienciacontufamilia {
            get {
                return ResourceManager.GetString("experienciacontufamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WITH YOUR FRIENDS.
        /// </summary>
        internal static string experienciacontusamigos {
            get {
                return ResourceManager.GetString("experienciacontusamigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPLORE ACTIVITIES.
        /// </summary>
        internal static string experienciaexploraractividades {
            get {
                return ResourceManager.GetString("experienciaexploraractividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOK FOR YOUR BUSINESS.
        /// </summary>
        internal static string experienciareserva {
            get {
                return ResourceManager.GetString("experienciareserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experience Wakana.
        /// </summary>
        internal static string experienciawakanat {
            get {
                return ResourceManager.GetString("experienciawakanat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPLORE OUR CAMPS.
        /// </summary>
        internal static string exploranuestroscampamentos {
            get {
                return ResourceManager.GetString("exploranuestroscampamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPLORE WAKANA.
        /// </summary>
        internal static string explorarwakana {
            get {
                return ResourceManager.GetString("explorarwakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activitites.
        /// </summary>
        internal static string facesactividades {
            get {
                return ResourceManager.GetString("facesactividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Happiness.
        /// </summary>
        internal static string facesbienvenidos {
            get {
                return ResourceManager.GetString("facesbienvenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake.
        /// </summary>
        internal static string faceslago {
            get {
                return ResourceManager.GetString("faceslago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faces.
        /// </summary>
        internal static string facesrostros {
            get {
                return ResourceManager.GetString("facesrostros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        internal static string facesvideos {
            get {
                return ResourceManager.GetString("facesvideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a · April / May - Weekends (Friday to Sunday) &lt;br/&gt;· June, July and August - Everyday &lt;br/&gt;· September / October - Weekends (Friday to Sunday)  &lt;br/&gt;&lt;br/&gt;*Note: If you belong to a group of 18 people or over, it is possible for yuo to book accommodation out of the season..
        /// </summary>
        internal static string faqabrilymayo {
            get {
                return ResourceManager.GetString("faqabrilymayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string faqactividades {
            get {
                return ResourceManager.GetString("faqactividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accommodation.
        /// </summary>
        internal static string faqalojamientost {
            get {
                return ResourceManager.GetString("faqalojamientost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When can the activities be carried out?.
        /// </summary>
        internal static string faqcuandosepueden {
            get {
                return ResourceManager.GetString("faqcuandosepueden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;We have a bar in our chill-out area by the lake, where you can have as much drinks as you want. For those guests who are going to spend a pleasant day in Wakana Lake without overnight, we also have a barbecue service for your enjoyment , Which includes a varied assortment of Iberian meat from the area, the gas barbecue and its gas bottle, and you can enjoy it anywhere in the open air inside our facilities.We also have different meal plans for those who spend the night in Wakana Lake. Both yurtas and tepees [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string faqdisponemosdebaren {
            get {
                return ResourceManager.GetString("faqdisponemosdebaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The reservoir of El Celemin extends over an area of 473 hectares and has a capacity of 43 cubic hectometers..
        /// </summary>
        internal static string faqelpantanodecelemin {
            get {
                return ResourceManager.GetString("faqelpantanodecelemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Many activities can be carried out in our complex, some of which requires assistance (*): &lt;br/&gt;&lt;br/&gt;· Arc Attack (archery) (*) &lt;br/&gt;· Canopy Park (Zip-line park and hanging bridges crossings) (*) &lt;br/&gt;· Spartan Trail 
        ///· Kayaking &lt;br/&gt;· Paddle-surf / Stand-up paddle &lt;br/&gt;· Bike routes 
        ///· Horse riding (*)&lt;br/&gt;.
        /// </summary>
        internal static string faqennuestrocomplejosepuedellevar {
            get {
                return ResourceManager.GetString("faqennuestrocomplejosepuedellevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is the water from the reservoir of El Celemin suitable for swimming?.
        /// </summary>
        internal static string faqesaptaparaelbaño {
            get {
                return ResourceManager.GetString("faqesaptaparaelbaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How big is Wakana Lake?.
        /// </summary>
        internal static string faqesmuygrandelpantano {
            get {
                return ResourceManager.GetString("faqesmuygrandelpantano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is there any age, height or weight limitations, or any recommendations to participate in the activities?.
        /// </summary>
        internal static string faqexisteunaedad {
            get {
                return ResourceManager.GetString("faqexisteunaedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is there a minimum/maximum number of participants in each activity?.
        /// </summary>
        internal static string faqexisteunnumerominimomax {
            get {
                return ResourceManager.GetString("faqexisteunnumerominimomax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is there a restaurant in Wakana Lake?.
        /// </summary>
        internal static string faqhayunrestaurante {
            get {
                return ResourceManager.GetString("faqhayunrestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installations.
        /// </summary>
        internal static string faqinstalaciones {
            get {
                return ResourceManager.GetString("faqinstalaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can I stay in Wakana Lake?, when?.
        /// </summary>
        internal static string faqmepuedoalojarenwakanalake {
            get {
                return ResourceManager.GetString("faqmepuedoalojarenwakanalake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, it is not possible. It is only possible to stay at the above mentioned types of accommodations..
        /// </summary>
        internal static string faqnonoesposible {
            get {
                return ResourceManager.GetString("faqnonoesposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A fee of  5,00 Euros per person is required to access Wakana Lake and a Disclaimer Form needs to be filled in and signed by any person entering the property..
        /// </summary>
        internal static string faqparapasar {
            get {
                return ResourceManager.GetString("faqparapasar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Of course. We have a total capacity of 150 places in different types of accommodations: Andalusian cortijo (60), tepees (48) and yurts (42).. Our opening calendar to the public is:&lt;br/&gt;&lt;br/&gt;· April / May - Weekends (Friday to Sunday)&lt;br/&gt;· June, July and August - Everyday&lt;br/&gt;· September / October - Weekends (Friday to Sunday)&lt;br/&gt;&lt;br/&gt;*Note: If you belong to a group of 18 people or over, it is possible for yuo to book accommodation out of the season..
        /// </summary>
        internal static string faqporsupuesto {
            get {
                return ResourceManager.GetString("faqporsupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What activities can I do at Wakana Lake?.
        /// </summary>
        internal static string faqqueact {
            get {
                return ResourceManager.GetString("faqqueact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What&apos;s Wakana Lake?.
        /// </summary>
        internal static string faqquees {
            get {
                return ResourceManager.GetString("faqquees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Which is the extension and capacity of the Celemin´s reservoir?.
        /// </summary>
        internal static string faqquextensiontienelepantano {
            get {
                return ResourceManager.GetString("faqquextensiontienelepantano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;u&gt;Requirements: &lt;/u&gt;&lt;br/&gt;· Arc Attack --- Minimum height of 1,40 m.&lt;br/&gt;· Canopy Park --- Minimum height of 1.40 m. / Maximum weight limit: 120,00 kg. &lt;br/&gt;&lt;br/&gt;&lt;u&gt;Important:&lt;/u&gt;&lt;br/&gt;· Appropriate closed footwear is required to participate in the activities. &lt;br/&gt;· Participants have to take into account that the Spartan Trail / Spartan Race includes mud ponds which may damage and stain you sportswear..
        /// </summary>
        internal static string faqrequisitosarcattack {
            get {
                return ResourceManager.GetString("faqrequisitosarcattack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is it possible to camp with tent or caravan / auto-caravan in Wakana Lake?.
        /// </summary>
        internal static string faqsepuedeacampar {
            get {
                return ResourceManager.GetString("faqsepuedeacampar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can anyone freely access to Wakana Lake?.
        /// </summary>
        internal static string faqsepuedeacceder {
            get {
                return ResourceManager.GetString("faqsepuedeacceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes, abolutely. We have carried out a complete analysis of the waters from the reservoir, which has shown that they are in excellent conditions for swimming..
        /// </summary>
        internal static string faqsitotalmente {
            get {
                return ResourceManager.GetString("faqsitotalmente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A minimum number of 18  participants is required in order to do the Spartan Trail, with an unlimited number of participants (duration of this activity: subjetc to the number of competitors and their physical conditions). &lt;br/&gt;· Canopy Park --- minimum/:1 / maximum: 25 (Estimated time: 2 hours). &lt;br/&gt;· Kayaks --- minimum/:1 / maximum: 25 (Estimated time: 2 hours). &lt;br/&gt;· Paddle-surf --- minimum/:1 / maximum: 25 (Estimated time: 2 hours). &lt;br/&gt;· Arc Attack --- minimum/:1 / maximum: 25 (Estimated time: 2 hours [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string faqsoloenlaspartantrall {
            get {
                return ResourceManager.GetString("faqsoloenlaspartantrall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequently Asked Questions.
        /// </summary>
        internal static string faqtitulo {
            get {
                return ResourceManager.GetString("faqtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake has an area of almost 20 hectares (additionally to the reservoir), where you can enjoy a multitud of activities..
        /// </summary>
        internal static string faqwakanalakecuentacasi20 {
            get {
                return ResourceManager.GetString("faqwakanalakecuentacasi20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake is a multiadventure complex in a natural environment, located in Los alcornocales Natural Park, at the edge of El Celemin´s reservoir. &lt;br/&gt;Wakana Lake is a place to share. Ideal for all types of clients, couples wishing to relax, families looking for a different experience that complements their holidays, or groups of friends or companies needing a customised program..
        /// </summary>
        internal static string faqwakanalakeesuncomplejo {
            get {
                return ResourceManager.GetString("faqwakanalakeesuncomplejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake se encuentra dentro del Parque Natural de los Alcornocales, conocido como la última Selva Virgen del sur de Europa. Gracias a la pureza de nuestras aguas existe una colonia de nutrias bastante importante en nuestra zona. Junto con las nutrias, zorros y venados entre otros comparten este idílico paraje..
        /// </summary>
        internal static string florawakanalake {
            get {
                return ResourceManager.GetString("florawakanalake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ARCHERY.
        /// </summary>
        internal static string gaarchery {
            get {
                return ResourceManager.GetString("gaarchery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOK NOW.
        /// </summary>
        internal static string gabooknow {
            get {
                return ResourceManager.GetString("gabooknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Community.
        /// </summary>
        internal static string gacomm {
            get {
                return ResourceManager.GetString("gacomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gallery.
        /// </summary>
        internal static string galeria {
            get {
                return ResourceManager.GetString("galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accomodation.
        /// </summary>
        internal static string gamacco {
            get {
                return ResourceManager.GetString("gamacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string gamact {
            get {
                return ResourceManager.GetString("gamact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string gamactiv {
            get {
                return ResourceManager.GetString("gamactiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map of Wakana.
        /// </summary>
        internal static string gamapof {
            get {
                return ResourceManager.GetString("gamapof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMPING.
        /// </summary>
        internal static string gamcamping {
            get {
                return ResourceManager.GetString("gamcamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        internal static string gamcontact {
            get {
                return ResourceManager.GetString("gamcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Activities.
        /// </summary>
        internal static string gamgeneral {
            get {
                return ResourceManager.GetString("gamgeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special Activities.
        /// </summary>
        internal static string gamspecial {
            get {
                return ResourceManager.GetString("gamspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Experience.
        /// </summary>
        internal static string gamtheexp {
            get {
                return ResourceManager.GetString("gamtheexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        internal static string gaplace {
            get {
                return ResourceManager.GetString("gaplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Conditions.
        /// </summary>
        internal static string gct {
            get {
                return ResourceManager.GetString("gct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • An identity document in place is required in order to stay at our establishment. (ID, Passport or Family book for children under 14 years)&lt;br/&gt;• Group activities must be booked at least fifteen days before, due to organizational issues.&lt;br/&gt;• It is required to bring from home bathroom utilities that you may need, such as towels, gels, toothpaste, etc.&lt;br/&gt;• It is prohibited to introduce explosive substances or materials, flammable or any other kind that could cause damages or disturb the rest of clients.  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string gctexto {
            get {
                return ResourceManager.GetString("gctexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will learn the techniques needed to ride and manage a horse. Enjoy the landscape offered by Wakana Lake and its surroundings..
        /// </summary>
        internal static string horsesaprenderas {
            get {
                return ResourceManager.GetString("horsesaprenderas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group of five people (max.).
        /// </summary>
        internal static string horsesgrupode5 {
            get {
                return ResourceManager.GetString("horsesgrupode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If it’s your first time:.
        /// </summary>
        internal static string horsesiestuprimeravez {
            get {
                return ResourceManager.GetString("horsesiestuprimeravez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comfortable trousers..
        /// </summary>
        internal static string horsespantalonlargo {
            get {
                return ResourceManager.GetString("horsespantalonlargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REQUIREMENTS.
        /// </summary>
        internal static string horsesrequisitos {
            get {
                return ResourceManager.GetString("horsesrequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have experience:.
        /// </summary>
        internal static string horsessitienesexp {
            get {
                return ResourceManager.GetString("horsessitienesexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let yourself be taken away by the idyllic place we find ourselves in..
        /// </summary>
        internal static string horsessolodejatellevar {
            get {
                return ResourceManager.GetString("horsessolodejatellevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferably boots or sports shoes..
        /// </summary>
        internal static string horseszapatosdedeporte {
            get {
                return ResourceManager.GetString("horseszapatosdedeporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enjoy all the wildlife that Wakana Lake has to offer.
        /// </summary>
        internal static string kayakdisfruta {
            get {
                return ResourceManager.GetString("kayakdisfruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experience nature from the water.
        /// </summary>
        internal static string kayakexpagua {
            get {
                return ResourceManager.GetString("kayakexpagua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No age limit.
        /// </summary>
        internal static string kayaksinlimite {
            get {
                return ResourceManager.GetString("kayaksinlimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gisela Pulido’s Water Sports Centre, 10 times World Champion of Kite Surf.
        /// </summary>
        internal static string kitecentrodedeportesacuaticos {
            get {
                return ResourceManager.GetString("kitecentrodedeportesacuaticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string kitedescargarinfo {
            get {
                return ResourceManager.GetString("kitedescargarinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Safely navigate the lake intended for kite surfing.
        /// </summary>
        internal static string kitedisfrutanavegando {
            get {
                return ResourceManager.GetString("kitedisfrutanavegando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take advantage of the powerful winds of the Levante.
        /// </summary>
        internal static string kitegozadelasvistas {
            get {
                return ResourceManager.GetString("kitegozadelasvistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enjoy the privileged sights of our environment at the same time as practicing sport.
        /// </summary>
        internal static string kitenavegaseguroennuestra {
            get {
                return ResourceManager.GetString("kitenavegaseguroennuestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THE MAGIC OF WAKANA.
        /// </summary>
        internal static string lamagiadewakana {
            get {
                return ResourceManager.GetString("lamagiadewakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USERS CONSENT/REVOCATION.
        /// </summary>
        internal static string lnconsentimiento {
            get {
                return ResourceManager.GetString("lnconsentimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;By selecting the check box the User accepts the privacy policy and consent for newsletters on&lt;/p&gt;
        ///                        &lt;p&gt;our services and activities as well as replies to any queries the user may have. Likewise the&lt;/p&gt;
        ///                        &lt;p&gt;consent giving for commercial purposes can be revoked by sending an email to&lt;/p&gt;
        ///                        &lt;p&gt;info@wakanalake.com or at the WAKANA LAKE  address.&lt;/p&gt;
        ///
        ///                        &lt;p&gt;WAKANA LAKE will be exonerated from any responsibility in conn [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lnconsentimientotexto {
            get {
                return ResourceManager.GetString("lnconsentimientotexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRAFFIC DATA.
        /// </summary>
        internal static string lndatosdetrafico {
            get {
                return ResourceManager.GetString("lndatosdetrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;Traffic data such as name of the access provider, IP address, date and time of access, links&lt;/p&gt;
        ///                        &lt;p&gt;from which you access and other information of a similar nature that your browsing of the&lt;/p&gt;
        ///                        &lt;p&gt;site can provide will be treated anonymously and with sole purpose of making statistics of&lt;/p&gt;
        ///                        &lt;p&gt;our visitor websites.&lt;/p&gt;
        ///                        &lt;p&gt;A method of collecting additional information from your visits to our service, is rec [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lndatosdetraficotexto {
            get {
                return ResourceManager.GetString("lndatosdetraficotexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXERCISE RIGHTS OF PRIVACY.
        /// </summary>
        internal static string lnejercicios {
            get {
                return ResourceManager.GetString("lnejercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;The user has the right to request and obtain, for free, information on their personal data&lt;/p&gt;
        ///                        &lt;p&gt;under treatment, its origin (which in our case will always be the forms located on the web)&lt;/p&gt;
        ///                        &lt;p&gt;and communications that may affect them.&lt;/p&gt;
        ///                        &lt;p&gt;Users can send a written communication to the address of WAKANA LAKE or an email&lt;/p&gt;
        ///                        &lt;p&gt;info@wakanalake.com, including in both cases, photocopy of their Identity Ca [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lnejerciciostexto {
            get {
                return ResourceManager.GetString("lnejerciciostexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACT FORMS AND TRADITIONAL MEDIA.
        /// </summary>
        internal static string lnformularios {
            get {
                return ResourceManager.GetString("lnformularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;The user is allowed to send unencrypted personal data via the contact form standard type,&lt;/p&gt;
        ///                        &lt;p&gt;and hosted on the servers of WAKANA LAKE. Personal data collected will be automatically&lt;/p&gt;
        ///                        &lt;p&gt;processed and incorporated into the corresponding files whose WAKANA LAKE is the owner&lt;/p&gt;
        ///                        &lt;p&gt;and are registered in the Spanish Data Protection Agency. The purpose of processing these&lt;/p&gt;
        ///                        &lt;p&gt;data will be for consultat [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lnformulariostexto {
            get {
                return ResourceManager.GetString("lnformulariostexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SECURITY MEASURES.
        /// </summary>
        internal static string lnmedidas {
            get {
                return ResourceManager.GetString("lnmedidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;WAKANA LAKE has adopted the security levels for protection of personal data required by&lt;/p&gt;
        ///                        &lt;p&gt;Law, and has installed all the means and technical measures at its disposal to prevent the&lt;/p&gt;
        ///                        &lt;p&gt;loss, misuse, alteration, unauthorized access and theft of the Personal Data provided.&lt;/p&gt;
        ///                        &lt;p&gt;However, the User must be aware that Internet security measures are not unassailable.&lt;/p&gt;.
        /// </summary>
        internal static string lnmedidastexto {
            get {
                return ResourceManager.GetString("lnmedidastexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRIVACY POLICY..
        /// </summary>
        internal static string lnpoliticadeprivacidad {
            get {
                return ResourceManager.GetString("lnpoliticadeprivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;In compliance with the Organic Law 15/1999, 13 December, for the protection of personal&lt;/p&gt;
        ///                        &lt;p&gt;data (LOPD), through this document, WAKANA LAKE informs users of this website about the&lt;/p&gt;
        ///                        &lt;p&gt;use and processing of personal data provided in its navigation and about the data protection&lt;/p&gt;
        ///                        &lt;p&gt;policy to be applied to such data.&lt;/p&gt;.
        /// </summary>
        internal static string lnpoliticatexto {
            get {
                return ResourceManager.GetString("lnpoliticatexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOCIAL NETWORKS.
        /// </summary>
        internal static string lnredes {
            get {
                return ResourceManager.GetString("lnredes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;WAKANA LAKE has a profile on Facebook and Instagram, being in all cases responsible for the&lt;/p&gt;
        ///                        &lt;p&gt;processing of data from its followers, fans, subscribers, commentators and other profiles of&lt;/p&gt;
        ///                        &lt;p&gt;users (hereinafter &quot;followers&quot;). The treatment performed by WAKANA LAKE on such data will&lt;/p&gt;
        ///                        &lt;p&gt;be, at most, that one allowed by the social network to corporate profiles. This way, WAKANA&lt;/p&gt;
        ///                        &lt;p&gt;LAKE  may info [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lnredestexto {
            get {
                return ResourceManager.GetString("lnredestexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOCATION.
        /// </summary>
        internal static string localizacion {
            get {
                return ResourceManager.GetString("localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        internal static string lugar {
            get {
                return ResourceManager.GetString("lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        internal static string mapa {
            get {
                return ResourceManager.GetString("mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Directions.
        /// </summary>
        internal static string mapdireccion {
            get {
                return ResourceManager.GetString("mapdireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake Map.
        /// </summary>
        internal static string mapmapadewakana {
            get {
                return ResourceManager.GetString("mapmapadewakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MORE INFO.
        /// </summary>
        internal static string masinfo {
            get {
                return ResourceManager.GetString("masinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My mission is for you to get closer to the value and importance of the environment for human being´s development. We will make you disconnect from your city mode into your natureself. I will be resolving any doubts you may have of our surroundings, flora and fauna. In conclusion, I will be guiding you so you can understand and enjoy all the pleasures that Mother Earth offers us..
        /// </summary>
        internal static string meealegre {
            get {
                return ResourceManager.GetString("meealegre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities Department.
        /// </summary>
        internal static string meedptoact {
            get {
                return ResourceManager.GetString("meedptoact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nature Department / Reception.
        /// </summary>
        internal static string meedptodenaturaleza {
            get {
                return ResourceManager.GetString("meedptodenaturaleza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivering happiness everyday.
        /// </summary>
        internal static string meeentregandofelicidad {
            get {
                return ResourceManager.GetString("meeentregandofelicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Together with Pitagoras and Jack, the sweet Ginger will not allow any mouse to sleep under your bed...
        /// </summary>
        internal static string meeginger {
            get {
                return ResourceManager.GetString("meeginger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My role in Wakana Lake is to corrdinate the activities department trying to transmit values thoughout sports..
        /// </summary>
        internal static string meejuanfuncion {
            get {
                return ResourceManager.GetString("meejuanfuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I am a sport lover, I have practided and still practicing nowadays several sports discipline, some of them at competition level..
        /// </summary>
        internal static string meejuanprimeraslineas {
            get {
                return ResourceManager.GetString("meejuanprimeraslineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I´m Moody, faithfull companion and your guardian during the nights of Wakana Lake..
        /// </summary>
        internal static string meemoody {
            get {
                return ResourceManager.GetString("meemoody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake Heroes.
        /// </summary>
        internal static string meewakanalakehe {
            get {
                return ResourceManager.GetString("meewakanalakehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MONTH.
        /// </summary>
        internal static string mes {
            get {
                return ResourceManager.GetString("mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pitágoras and Jack, little lions will not allow any mouse to sleep under your bed..
        /// </summary>
        internal static string mmeepitagoras {
            get {
                return ResourceManager.GetString("mmeepitagoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROMOTIONS.
        /// </summary>
        internal static string ofertas {
            get {
                return ResourceManager.GetString("ofertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Águila imperial.
        /// </summary>
        internal static string ornitaguilaimp {
            get {
                return ResourceManager.GetString("ornitaguilaimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Águila pescadora.
        /// </summary>
        internal static string ornitaguilapescadora {
            get {
                return ResourceManager.GetString("ornitaguilapescadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cádiz es la provincia con mayor diversidad ornitológica de la península debido a su situación geográfica. Son varias especies destacadas las que nos visitan en Wakana Lake como por ejemplo:.
        /// </summary>
        internal static string ornitcadizeslaprovincia {
            get {
                return ResourceManager.GetString("ornitcadizeslaprovincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Milano negro.
        /// </summary>
        internal static string ornitmilanonegro {
            get {
                return ResourceManager.GetString("ornitmilanonegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gisela Pulido’s Water Sports Centre, 10 times World Champion of Kite Surf.
        /// </summary>
        internal static string paddlecentrodedeportes {
            get {
                return ResourceManager.GetString("paddlecentrodedeportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See the sights from the vantage point of the paddle board.
        /// </summary>
        internal static string paddledisfruta {
            get {
                return ResourceManager.GetString("paddledisfruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Individual or in groups.
        /// </summary>
        internal static string paddlesolooengrupos {
            get {
                return ResourceManager.GetString("paddlesolooengrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Improve balance and coordination.
        /// </summary>
        internal static string paddletrabajaelequilibrio {
            get {
                return ResourceManager.GetString("paddletrabajaelequilibrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTNER WITH US.
        /// </summary>
        internal static string partnerscolabora {
            get {
                return ResourceManager.GetString("partnerscolabora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPLORE ACTIVITIES.
        /// </summary>
        internal static string partnersexplorar {
            get {
                return ResourceManager.GetString("partnersexplorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our Partners.
        /// </summary>
        internal static string partnersnuestros {
            get {
                return ResourceManager.GetString("partnersnuestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activities.
        /// </summary>
        internal static string pmact {
            get {
                return ResourceManager.GetString("pmact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accomodation.
        /// </summary>
        internal static string pmalojamientos {
            get {
                return ResourceManager.GetString("pmalojamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andalusian Cortijo.
        /// </summary>
        internal static string pmandalusian {
            get {
                return ResourceManager.GetString("pmandalusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEGAL NOTICE.
        /// </summary>
        internal static string pmavisolegal {
            get {
                return ResourceManager.GetString("pmavisolegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bocalan Camps.
        /// </summary>
        internal static string pmbocalan {
            get {
                return ResourceManager.GetString("pmbocalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camps.
        /// </summary>
        internal static string pmcamps {
            get {
                return ResourceManager.GetString("pmcamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Community.
        /// </summary>
        internal static string pmcomunidad {
            get {
                return ResourceManager.GetString("pmcomunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAL CONDITIONS.
        /// </summary>
        internal static string pmcondicionesgenerales {
            get {
                return ResourceManager.GetString("pmcondicionesgenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACT.
        /// </summary>
        internal static string pmcontacto {
            get {
                return ResourceManager.GetString("pmcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        internal static string pmequipo {
            get {
                return ResourceManager.GetString("pmequipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string pmevents {
            get {
                return ResourceManager.GetString("pmevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gallery.
        /// </summary>
        internal static string pmgaleria {
            get {
                return ResourceManager.GetString("pmgaleria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOCATION.
        /// </summary>
        internal static string pmlocalizacion {
            get {
                return ResourceManager.GetString("pmlocalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        internal static string pmlugar {
            get {
                return ResourceManager.GetString("pmlugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        internal static string pmmapa {
            get {
                return ResourceManager.GetString("pmmapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Us.
        /// </summary>
        internal static string pmnosotros {
            get {
                return ResourceManager.GetString("pmnosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partners.
        /// </summary>
        internal static string pmpartners {
            get {
                return ResourceManager.GetString("pmpartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELATION POLICY.
        /// </summary>
        internal static string pmpoliticacancelacion {
            get {
                return ResourceManager.GetString("pmpoliticacancelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVATION POLICY.
        /// </summary>
        internal static string pmpoliticareserva {
            get {
                return ResourceManager.GetString("pmpoliticareserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAQ.
        /// </summary>
        internal static string pmpreguntas {
            get {
                return ResourceManager.GetString("pmpreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOKING.
        /// </summary>
        internal static string pmreserva {
            get {
                return ResourceManager.GetString("pmreserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a School Camps.
        /// </summary>
        internal static string pmschoolcamps {
            get {
                return ResourceManager.GetString("pmschoolcamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spartan Race Camps.
        /// </summary>
        internal static string pmspartan {
            get {
                return ResourceManager.GetString("pmspartan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wakana Lake Summer Camps.
        /// </summary>
        internal static string pmsummercamps {
            get {
                return ResourceManager.GetString("pmsummercamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tepees.
        /// </summary>
        internal static string pmtipis {
            get {
                return ResourceManager.GetString("pmtipis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yurts.
        /// </summary>
        internal static string pmyurtas {
            get {
                return ResourceManager.GetString("pmyurtas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELATION POLICY.
        /// </summary>
        internal static string politicadecancelacion {
            get {
                return ResourceManager.GetString("politicadecancelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVATION POLICY.
        /// </summary>
        internal static string politicadereserva {
            get {
                return ResourceManager.GetString("politicadereserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAQ.
        /// </summary>
        internal static string preguntasfrecuentes {
            get {
                return ResourceManager.GetString("preguntasfrecuentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOOKING.
        /// </summary>
        internal static string reserva {
            get {
                return ResourceManager.GetString("reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a • As a booking guarantee, we request a credit card (card holder, card number, expire date and cvc), bank account number or bank account transfer (send bank proof by e-mail)&lt;/br&gt;• The reservation fee is 20% for groups at the moment of confirmation.&lt;/br&gt;• The total amount will be paid ALWAYS before arrival date.&lt;/br&gt;• Minimum stay is two nights for any time in the year, except for long weekends, Easter holidays, and bank holidays in which case the minimum stay is three nights.&lt;/br&gt;• Payments placed with credi [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string rppuntos {
            get {
                return ResourceManager.GetString("rppuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservation Policy.
        /// </summary>
        internal static string rptitulo {
            get {
                return ResourceManager.GetString("rptitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABOUT US.
        /// </summary>
        internal static string sobrenosotros {
            get {
                return ResourceManager.GetString("sobrenosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spartan Race Camps.
        /// </summary>
        internal static string spartanracecampstitulo {
            get {
                return ResourceManager.GetString("spartanracecampstitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summer Camps.
        /// </summary>
        internal static string summercampscampamentodeverano {
            get {
                return ResourceManager.GetString("summercampscampamentodeverano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2017 DATES.
        /// </summary>
        internal static string summercampsfechas2017 {
            get {
                return ResourceManager.GetString("summercampsfechas2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MORE INFO.
        /// </summary>
        internal static string summercampsmasinfo {
            get {
                return ResourceManager.GetString("summercampsmasinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICES.
        /// </summary>
        internal static string tepeesprecios {
            get {
                return ResourceManager.GetString("tepeesprecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tepees.
        /// </summary>
        internal static string tepeestipis {
            get {
                return ResourceManager.GetString("tepeestipis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tepees.
        /// </summary>
        internal static string tipis {
            get {
                return ResourceManager.GetString("tipis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOUR HOME AWAY FROM HOME.
        /// </summary>
        internal static string tuhogarfueradetuhogar {
            get {
                return ResourceManager.GetString("tuhogarfueradetuhogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A SUMMER OF POSSIBILITIES.
        /// </summary>
        internal static string unveranodeposibilidades {
            get {
                return ResourceManager.GetString("unveranodeposibilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIDEO.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VISIT ACCOMMODATION.
        /// </summary>
        internal static string visitaralojamientos {
            get {
                return ResourceManager.GetString("visitaralojamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yurts.
        /// </summary>
        internal static string yurtas {
            get {
                return ResourceManager.GetString("yurtas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICES.
        /// </summary>
        internal static string yurtasprecios {
            get {
                return ResourceManager.GetString("yurtasprecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yurts.
        /// </summary>
        internal static string yurtasyurtas {
            get {
                return ResourceManager.GetString("yurtasyurtas", resourceCulture);
            }
        }
    }
}
